# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(767, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_text = QtWidgets.QLabel(self.centralwidget)
        self.label_text.setGeometry(QtCore.QRect(140, 110, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_text.setFont(font)
        self.label_text.setObjectName("label_text")
        self.play_bt = QtWidgets.QPushButton(self.centralwidget)
        self.play_bt.setGeometry(QtCore.QRect(250, 250, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.play_bt.setFont(font)
        self.play_bt.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color: red;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: pink;\n"
"}")
        self.play_bt.setObjectName("play_bt")
        self.eng = QtWidgets.QPushButton(self.centralwidget)
        self.eng.setGeometry(QtCore.QRect(570, 500, 93, 28))
        self.eng.setObjectName("eng")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(670, 500, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.rock = QtWidgets.QPushButton(self.centralwidget)
        self.rock.setGeometry(QtCore.QRect(90, 90, 131, 101))
        self.rock.setObjectName("rock")
        self.paper = QtWidgets.QPushButton(self.centralwidget)
        self.paper.setGeometry(QtCore.QRect(290, 90, 131, 101))
        self.paper.setObjectName("paper")
        self.scissors = QtWidgets.QPushButton(self.centralwidget)
        self.scissors.setGeometry(QtCore.QRect(520, 90, 131, 101))
        self.scissors.setObjectName("scissors")
        self.time_text = QtWidgets.QLabel(self.centralwidget)
        self.time_text.setGeometry(QtCore.QRect(170, 20, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.time_text.setFont(font)
        self.time_text.setObjectName("time_text")
        self.time_left = QtWidgets.QLabel(self.centralwidget)
        self.time_left.setGeometry(QtCore.QRect(480, 20, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.time_left.setFont(font)
        self.time_left.setObjectName("time_left")
        self.robot_text = QtWidgets.QLabel(self.centralwidget)
        self.robot_text.setGeometry(QtCore.QRect(220, 360, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.robot_text.setFont(font)
        self.robot_text.setObjectName("robot_text")
        self.result = QtWidgets.QPushButton(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(210, 480, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setStyleSheet("QPushButton {\n"
"    border-radius: 8px;\n"
"    background-color: red;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: pink;\n"
"}")
        self.result.setObjectName("result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_text.setText(_translate("MainWindow", "Камінь    Ножиці    Бумага"))
        self.play_bt.setText(_translate("MainWindow", "Грати"))
        self.eng.setText(_translate("MainWindow", "Eng"))
        self.pushButton_3.setText(_translate("MainWindow", "Ukr"))
        self.rock.setText(_translate("MainWindow", "Камінь"))
        self.paper.setText(_translate("MainWindow", "Папір"))
        self.scissors.setText(_translate("MainWindow", "Ножиці"))
        self.time_text.setText(_translate("MainWindow", "Text time"))
        self.time_left.setText(_translate("MainWindow", "10"))
        self.robot_text.setText(_translate("MainWindow", "Robot choice"))
        self.result.setText(_translate("MainWindow", "Результат"))
